networks:
  localai:
    external: true

services:
  open-webui:
    container_name: open-webui
    image:
      ghcr.io/open-webui/open-webui:main
    #ports:
    #  - 8081:8080
    volumes:
      - ./open-webui:/app/backend/data
    restart: always
    devices:
      - /dev/snd
    env_file:
      - .env
    networks:
      - localai 
