networks:
  localai:
    external: true

services:

  comfyui:
    init: true
    container_name: comfyui
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot:cu124-megapak"
    ports:
      - "0.0.0.0:8188:8188"
    networks:
      - localai
    volumes:
      - "./storage:/root"
      - "../../models/ComfyUI:/root/ComfyUI/models"
      - "../../input/ComfyUI:/root/ComfyUI/input"
      - "../../output/ComfyUI:/root/ComfyUI/output"
      - "../../workflows/ComfyUI:/root/ComfyUI/user/default/workflows/"
    environment:
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
