---
cachedir: '/ai/cache/'
modeldir: 'models/'
packs:
  - name: 'Stable Diffusion Video 14fps'
    app: ComfyUI
    output: video
    models:
      - filename: 'svd.safetensors'
        url: 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid/resolve/main/svd.safetensors'
        sha256: '3e0994626df395a3831de024f11b2d9d241143bb6f16e2efbacced248aa18ce0'
        path: 'ComfyUI/checkpoints/'
        type: checkpoint 

  - name: 'Stable Diffusion Video 25fps' 
    app: ComfyUI
    output: video
    models:
      - filename: 'svd_xt.safetensors' 
        url: 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/resolve/main/svd_xt.safetensors'
        sha256: 'b2652c23d64a1da5f14d55011b9b6dce55f2e72e395719f1cd1f8a079b00a451' 
        path: 'ComfyUI/checkpoints/'
        type: checkpoint 

  - name: 'Mochi fp16' 
    app: ComfyUI
    output: video
    models:
      - filename: 'mochi_preview_bf16.safetensors' 
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/diffusion_models/mochi_preview_bf16.safetensors' 
        sha256: 'e445b9b393c70c431543b062cc16ee29b5dc4dc187487fa3e1f5a4b6162c8be1'
        path: 'ComfyUI/diffusion_models/'
        type: checkpoint 
      - filename: '5xxl_fp16.safetensors' 
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/text_encoders/t5xxl_fp16.safetensors'
        sha256: '6e480b09fae049a72d2a8c5fbccb8d3e92febeb233bbe9dfe7256958a9167635'
        path: 'ComfyUI/text_encoders/'
        type: textencoder
      - filename: 'mochi_vae.safetensors'
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/vae/mochi_vae.safetensors'
        sha256: '1be451cec94b911980406169286babc5269e7cf6a94bbbbdf45e8d3f2c961083'
        path: 'ComfyUI/vae/'
        type: vae

  - name: 'Mochi fp8' 
    app: ComfyUI
    output: video
    models:
      - filename: 'mochi_preview_fp8_scaled.safetensors' 
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/diffusion_models/mochi_preview_fp8_scaled.safetensors' 
        sha256: '8a6475b5380c90461a40d5c08ad574a5ad5ac4e6047e5f5f3f294df363f50705'
        path: 'ComfyUI/diffusion_models/'
        type: checkpoint 
      - filename: 't5xxl_fp8_e4m3fn_scaled.safetensors' 
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/text_encoders/t5xxl_fp8_e4m3fn_scaled.safetensors'
        sha256: 'a498f0485dc9536735258018417c3fd7758dc3bccc0a645feaa472b34955557a'
        path: 'ComfyUI/text_encoders/'
        type: textencoder
      - filename: 'mochi_vae.safetensors'
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/vae/mochi_vae.safetensors'
        sha256: '1be451cec94b911980406169286babc5269e7cf6a94bbbbdf45e8d3f2c961083'
        path: 'ComfyUI/vae/'
        type: vae

  - name: 'LTX Video'
    app: ComfyUI
    output: video
    models:
      - filename: 'ltx-video-2b-v0.9.5.safetensors'
        url: 'https://huggingface.co/Lightricks/LTX-Video/resolve/main/ltx-video-2b-v0.9.5.safetensors'
        sha256: '720d15c9f19f7d0f6b2a92bbbc34410e2cfb2f6856a100b38f734fbf973d4adf'
        path: 'ComfyUI/checkpoints/'
        type: checkpoint
      - filename: 't5xxl_fp16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/text_encoders/t5xxl_fp16.safetensors'
        sha256: '6e480b09fae049a72d2a8c5fbccb8d3e92febeb233bbe9dfe7256958a9167635'
        path: 'ComfyUI/text_encoders/'
        type: textencoder

  - name: 'Hunyuan Video'
    app: ComfyUI
    output: video
    models:
      - filename: 'clip_l.safetensors'
        url: 'https://huggingface.co/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/text_encoders/clip_l.safetensors'
        sha256: '660c6f5b1abae9dc498ac2d21e1347d2abdb0cf6c0c0c8576cd796491d9a6cdd'
        path: 'ComfyUI/text_encoders/'
        type: textencoder
      - filename: 'llava_llama3_fp8_scaled.safetensors'
        url: 'https://huggingface.co/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/text_encoders/llava_llama3_fp8_scaled.safetensors'
        sha256: '2f0c3ad255c282cead3f078753af37d19099cafcfc8265bbbd511f133e7af250'
        path: 'ComfyUI/text_encoders/'
        type: textencoder
      - filename: 'hunyuan_video_vae_bf16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/vae/hunyuan_video_vae_bf16.safetensors'
        sha256: 'e8f8553275406d84ccf22e7a47601650d8f98bdb8aa9ccfdd6506b57a9701aed'
        path: 'ComfyUI/vae/'
        type: vae
      - filename: 'clip_vision_h.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors'
        sha256: '64a7ef761bfccbadbaa3da77366aac4185a6c58fa5de5f589b42a65bcc21f161'
        path: 'ComfyUI/clip_vision/'
        type: clip_vision
      - filename: 'hunyuan_video_image_to_video_720p_bf16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/diffusion_models/hunyuan_video_image_to_video_720p_bf16.safetensors'
        sha256: '8b9c3c7bac5775bce0d3eb0dae0fcc37fb472456f1bb4e7e6c4fc045095e93b1'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'hunyuan_video_t2v_720p_bf16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/diffusion_models/hunyuan_video_t2v_720p_bf16.safetensors'
        sha256: 'c6ff2d107f0fec571fe276ad847468404ed01855c28c0be8859c3b311daec52a'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: ''
        url: 'https://huggingface.co/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/clip_vision/llava_llama3_vision.safetensors'
        sha256: '7d0f89bf7860815f3a994b9bdae8ebe3a29c161825d03ca9262cb13b0c973aa6'
        path: 'ComfyUI/models/clip_vision/'
        type: clip_vision

  - name: 'Nvidia Cosmos'
    app: ComfyUI
    output: video
    models:
      - filename: 'oldt5_xxl_fp8_e4m3fn_scaled.safetensors'
        url: 'https://huggingface.co/comfyanonymous/cosmos_1.0_text_encoder_and_VAE_ComfyUI/resolve/main/text_encoders/oldt5_xxl_fp8_e4m3fn_scaled.safetensors'
        sha256: '1d0dd711ec9866173d4b39e86db3f45e1614a4e3f84919556f854f773352ea81'
        path: 'ComfyUI/text_encoders/'
        type: text_encoder
      - filename: 'cosmos_cv8x8x8_1.0.safetensors'
        url: 'https://huggingface.co/comfyanonymous/cosmos_1.0_text_encoder_and_VAE_ComfyUI/resolve/main/vae/cosmos_cv8x8x8_1.0.safetensors'
        sha256: 'e4478fa8629160d16262276e52bdea91ecef636b005a2a29e93a3d7764e0863b'
        path: 'ComfyUI/vae/'
        type: vae
      - filename: 'Cosmos-1_0-Diffusion-7B-Text2World.safetensors'
        url: 'https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-7B-Text2World.safetensors'
        sha256: 'd2bfe066c931090ea89dfa55f86c0f639b304179e813cac9a533d3a69fadc450'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'Cosmos-1_0-Diffusion-7B-Video2World.safetensors'
        url: 'https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-7B-Video2World.safetensors'
        sha256: '72025138802d969d50ca194126d65e2fe5d1900e4033251a4f61dc4b7e29e0fe'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'Cosmos-1_0-Diffusion-14B-Text2World.safetensors'
        url: 'https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-14B-Text2World.safetensors'
        sha256: '17e6530e5d3fcb04b79f6e99557adc2e401bbd1cac4d17ba1e12feb5a2f1c3f1'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'Cosmos-1_0-Diffusion-14B-Video2World.safetensors'
        url: 'https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-14B-Video2World.safetensors'
        sha256: '9da37d47c7847478dcc14ba18c470a73e0d3e4326c398a8d81434bbdccb18324'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model

  - name: 'Wan 2.1'
    app: ComfyUI
    output: video
    models:
      - filename: 'umt5_xxl_fp8_e4m3fn_scaled.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors'
        sha256: 'c3355d30191f1f066b26d93fba017ae9809dce6c627dda5f6a66eaa651204f68'
        path: 'ComfyUI/text_encoders/'
        type: text_encoder
      - filename: 'umt5_xxl_fp16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp16.safetensors'
        sha256: '7b8850f1961e1cf8a77cca4c964a358d303f490833c6c087d0cff4b2f99db2af'
        path: 'ComfyUI/text_encoders/'
        type: text_encoder
      - filename: 'wan_2.1_vae.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors'
        sha256: '2fc39d31359a4b0a64f55876d8ff7fa8d780956ae2cb13463b0223e15148976b'
        path: 'ComfyUI/vae/'
        type: vae
      - filename: 'wan2.1_i2v_480p_14B_bf16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_i2v_480p_14B_bf16.safetensors'
        sha256: 'c058a4ac5363c35d1ab4dd3bdec788c23b267fa42a0d7c68aba599f2f74600c9'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_i2v_480p_14B_fp16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_i2v_480p_14B_fp16.safetensors'
        sha256: '27988f6b510eb8d5fdd7485671b54897f8683f2bba7a772c5671be21d3491253'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_i2v_480p_14B_fp8_e4m3fn.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_i2v_480p_14B_fp8_e4m3fn.safetensors'
        sha256: '0ca75338e7a47ca7cacddb7e626647e65829c497387f718ecb6ea0bae456944a'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_i2v_480p_14B_fp8_scaled.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_i2v_480p_14B_fp8_scaled.safetensors'
        sha256: 'b2de21b99b2e72cb0ff15253b07e926f26e7cf1b7e229efc32f94ad1f1ed9395'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_i2v_720p_14B_bf16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_i2v_720p_14B_bf16.safetensors'
        sha256: '8ef7ea5bf9eea636b9b3ebd84c40671b4a18ae2704cb4c8595cb5b25c1d8e8b9'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_i2v_720p_14B_fp16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_i2v_720p_14B_fp16.safetensors'
        sha256: '7664fe075b3c82dcecf89012ad3429eee41ee9f10d476f60bc2d2ae3c4ca986c'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_i2v_720p_14B_fp8_e4m3fn.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_i2v_720p_14B_fp8_e4m3fn.safetensors'
        sha256: 'b2051cd29d6b2f0c924fa7a3e78a4772f0134d7b059f21590dcce416f4f6cbe8'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_i2v_720p_14B_fp8_scaled.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_i2v_720p_14B_fp8_scaled.safetensors'
        sha256: '6d7a34b63b70eb608324e546d979167a5e787ac6bca3528e63f54a11572d66aa'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_t2v_1.3B_bf16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_t2v_1.3B_bf16.safetensors'
        sha256: '6f999b0d6cb9a72b3d98ac386ed96f57f8cecae13994a69232514ea4974ad5fd'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_t2v_1.3B_fp16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_t2v_1.3B_fp16.safetensors'
        sha256: 'be531024cd9018cb5b48c40cfbb6a6191645b1c792eb8bf4f8c1c6e10f924dc5'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_t2v_14B_bf16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_t2v_14B_bf16.safetensors'
        sha256: '193535c6450045f718df5f011de6d94d49bd9b13f37ca0412500f050dbbb01a8'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_t2v_14B_fp16.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_t2v_14B_fp16.safetensors'
        sha256: '46c27d3693bf2475990a912e08bf67fc6e6cd5396eab87b5e8dd1fcd3651364a'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_t2v_14B_fp8_e4m3fn.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_t2v_14B_fp8_e4m3fn.safetensors'
        sha256: '2ee88ab18d7ed7691c5b7f8bdc3d0a9815e6efe75499287564830fd209d3cdfb'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
      - filename: 'wan2.1_t2v_14B_fp8_scaled.safetensors'
        url: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_t2v_14B_fp8_scaled.safetensors'
        sha256: '2e39adde59c5e0e90edbb35873126b0d67928b5c11c501e384e976d6dc597cce'
        path: 'ComfyUI/diffusion_models/'
        type: diffusion_model
