---
cachedir: '/ai/cache/'
modeldir: 'models/'
packs:
  - name: 'Stable Diffusion Video 14fps'
    app: ComfyUI
    output: video
    models:
      - filename: 'svd.safetensors'
        url: 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid/resolve/main/svd.safetensors'
        sha256: '3e0994626df395a3831de024f11b2d9d241143bb6f16e2efbacced248aa18ce0'
        path: 'ComfyUI/checkpoints/'
        type: checkpoint 

  - name: 'Stable Diffusion Video 25fps' 
    app: ComfyUI
    output: video
    models:
      - filename: 'svd_xt.safetensors' 
        url: 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/resolve/main/svd_xt.safetensors'
        sha256: 'b2652c23d64a1da5f14d55011b9b6dce55f2e72e395719f1cd1f8a079b00a451' 
        path: 'ComfyUI/checkpoints/'
        type: checkpoint 

  - name: 'Mochi fp16' 
    app: ComfyUI
    output: video
    models:
      - filename: 'mochi_preview_bf16.safetensors' 
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/diffusion_models/mochi_preview_bf16.safetensors' 
        sha256: 'e445b9b393c70c431543b062cc16ee29b5dc4dc187487fa3e1f5a4b6162c8be1'
        path: 'ComfyUI/diffusion_models/'
        type: checkpoint 
      - filename: '5xxl_fp16.safetensors' 
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/text_encoders/t5xxl_fp16.safetensors'
        sha256: '6e480b09fae049a72d2a8c5fbccb8d3e92febeb233bbe9dfe7256958a9167635'
        path: 'ComfyUI/text_encoders/'
        type: textencoder
      - filename: 'mochi_vae.safetensors'
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/vae/mochi_vae.safetensors'
        sha256: '1be451cec94b911980406169286babc5269e7cf6a94bbbbdf45e8d3f2c961083'
        path: 'ComfyUI/vae/'
        type: vae

  - name: 'Mochi fp8' 
    app: ComfyUI
    output: video
    models:
      - filename: 'mochi_preview_fp8_scaled.safetensors' 
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/diffusion_models/mochi_preview_fp8_scaled.safetensors' 
        sha256: '8a6475b5380c90461a40d5c08ad574a5ad5ac4e6047e5f5f3f294df363f50705'
        path: 'ComfyUI/diffusion_models/'
        type: checkpoint 
      - filename: 't5xxl_fp8_e4m3fn_scaled.safetensors' 
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/text_encoders/t5xxl_fp8_e4m3fn_scaled.safetensors'
        sha256: 'a498f0485dc9536735258018417c3fd7758dc3bccc0a645feaa472b34955557a'
        path: 'ComfyUI/text_encoders/'
        type: textencoder
      - filename: 'mochi_vae.safetensors'
        url: 'https://huggingface.co/Comfy-Org/mochi_preview_repackaged/resolve/main/split_files/vae/mochi_vae.safetensors'
        sha256: '1be451cec94b911980406169286babc5269e7cf6a94bbbbdf45e8d3f2c961083'
        path: 'ComfyUI/vae/'
        type: vae

